MVC/Models/EmployeeInfo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int EmpNo { get; set; }
        public string EmpName { get; set; }
        public string DeptName { get; set; }
        public string Designation { get; set; }
        public decimal Salary { get; set; }
    }
}

MVC/Models/Model.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployEntity : DbContext
    {
        public EmployEntity()
            : base("name=EmployEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeInfo> EmployeeInfoes { get; set; }
    }
}

MVC/Models/Model.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Lenovo\source\repos\WebApiMVC\MVC\Models\Model.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MVC/Models/Model.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MVC/Controllers/EmployMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using MVC.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net;
using System.Threading.Tasks;

namespace MVC.Controllers
{
    public class EmployMVCController : Controller
    {
        HttpClient req;
        string url = "https://localhost:44375/api/";
        public EmployMVCController()
        { 
            req = new HttpClient();
            req.BaseAddress = new Uri(url);
            req.DefaultRequestHeaders.Accept.Clear();
            req.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: EmployMVC
        public ViewResult GetAllEmployee()
        { 
            IEnumerable<EmployeeInfo> employList;
            HttpResponseMessage response = req.GetAsync("getAllEmployee").Result;
            employList = response.Content.ReadAsAsync<IEnumerable<EmployeeInfo>>().Result;
            return View(employList);
        }


        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(EmployeeInfo employ)
        {
            
                HttpResponseMessage response = req.PostAsJsonAsync("createEmploy", employ).Result;
                return RedirectToAction("getAllEmployee");
               
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int id1 = Convert.ToInt32(id);
            HttpResponseMessage response = req.GetAsync("edit/"+ id1).Result;

            EmployeeInfo info = response.Content.ReadAsAsync<EmployeeInfo>().Result;
            if(info == null)
            {
                return HttpNotFound();
            }
            return View(info);
        }

        [HttpPost]
        public ActionResult Edit(EmployeeInfo employ)
        {
            HttpResponseMessage response = req.PutAsJsonAsync("update", employ).Result;
            
            return RedirectToAction("getAllEmployee");
        }

        public ActionResult Delete(int id)
        {
            if (id.ToString() == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            HttpResponseMessage response = req.DeleteAsync("delete/" + id).Result;
          
            return RedirectToAction("getAllEmployee");
        }

    }
}

MVC/Views/EmployMVC/Create.cshtml
@model MVC.Models.EmployeeInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


<div class="row">
    <div class="col-md-6 col-lg-offset-3">
        @using (Html.BeginForm())
        {
        <form>
            <div class="form-group">
                @Html.LabelFor(model => model.EmpName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DeptName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DeptName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DeptName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group my-5">
                <div class="row ">
                    <div class="col-sm-6">
                        @Html.HiddenFor(model => model.EmpNo)

                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>

                    <div class="col-sm-6">
                        <button type="reset" class="btn btn-info">Reset</button>
                    </div>

                </div>
            </div>


            <div class="form-group">
                @Html.ActionLink("Back to List", "getAllEmployee")
            </div>

        </form>

        }

       
    </div>
</div>

@section scripts
{

    @Scripts.Render("~/bundles/jqueryval")
    
}

MVC/Views/EmployMVC/Edit.cshtml
@model MVC.Models.EmployeeInfo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="row">
    <div class="col-md-6 col-lg-offset-3">
        @using (Html.BeginForm())
        {

        <form>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.EmpNo)

            <div class="form-group">
                @Html.LabelFor(model => model.EmpName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DeptName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DeptName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DeptName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group my-5">
                <button type="submit" class="btn btn-primary">Edit</button>

            </div>


            <div class="form-group">
                @Html.ActionLink("Back to List", "getAllEmployee")
            </div>

        </form>

        }


    </div>
</div>

@section scripts
{

    @Scripts.Render("~/bundles/jqueryval")

}

MVC/Views/EmployMVC/GetAllEmployee.cshtml
@model IEnumerable<MVC.Models.EmployeeInfo>

@{
    ViewBag.Title = "GetAllEmployee";
}

<h2>GetAllEmployee</h2>

<p><a href="@Url.Action("create","EmployMVC")" class="btn btn-info btn-md">Create</a></p>

<table class="table table-striped">
    <thead class="tab-content">
        <tr>
            <th>Emp Name</th>

            <th>Dept Name</th>

            <th>Designation</th>

            <th>Salary</th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model)
        {

        <tr>
            <td>@Html.DisplayFor(model => i.EmpName)</td>

            <td>@Html.DisplayFor(model => i.DeptName)</td>

            <td>@Html.DisplayFor(model => i.Designation)</td>

            <td>@Html.DisplayFor(model => i.Salary)</td>

            <td>
            @Html.ActionLink("Edit", "Edit", new { id = i.EmpNo },null) |
            @Html.ActionLink("Delete", "delete", new { id = i.EmpNo },null)
                </td>
        </tr>

        }
    </tbody>
</table>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("All Employees", "getAllEmployee", "EmployMVC")</li>
                    <li>@Html.ActionLink("Create", "Create", "EmployMVC")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>